const typeCode = {
	custom: 0,
	ascii: 1,
	bigint: 2,
	blob: 3,
	boolean: 4,
	counter: 5,
	decimal: 6,
	double: 7,
	float: 8,
	int: 9,
	text: 10,
	timestamp: 11,
	uuid: 12,
	varchar: 13,
	varint: 14,
	timeuuid: 15,
	inet: 16,
	date: 17,
	time: 18,
	smallint: 19,
	tinyint: 20,
	list: 21,
	map: 22,
	set: 23,
	udt: 24,
	tuple: 25,
};
const nativeTypes = [
	typeCode['ascii'],
	typeCode['bigint'],
	typeCode['blob'],
	typeCode['boolean'],
	typeCode['counter'],
	typeCode['date'],
	typeCode['decimal'],
	typeCode['double'],
	typeCode['float'],
	typeCode['inet'],
	typeCode['int'],
	typeCode['smallint'],
	typeCode['text'],
	typeCode['time'],
	typeCode['timestamp'],
	typeCode['timeuuid'],
	typeCode['tinyint'],
	typeCode['uuid'],
	typeCode['varchar'],
	typeCode['varint'],
];

export { typeCode, nativeTypes };
